services:

  dev-db:
    image: mysql:8.0.19
    environment:
      - MYSQL_DATABASE=dbUsers
      - MYSQL_ROOT_PASSWORD=db-bt-22
    restart: always
    volumes:
      - dev-db-data:/var/lib/mysql
    networks:
      - spring-mysql
    ports:
      - "3333:3306"

  dev-mongodb:
    image: mongo:7.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongo-secret
      MONGO_INITDB_DATABASE: dbBooks
    volumes:
      - dev-mongo-data:/data/db
    networks:
      - spring-mysql
    ports:
      - "3334:27017"

volumes:
  dev-db-data: {}
  dev-mongo-data: {}

networks:
  spring-mysql: {}